###############################################################################
# Navigation                                                                  #
###############################################################################
alias ..='cd ..'
alias ...='cd ../..'

###############################################################################
# Listing                                                                     #
###############################################################################
alias ll='ls -l'
alias lla='ls -la'

###############################################################################
# Git                                                                         #
###############################################################################
alias gcl='git clone'
alias ga='git add'
alias gc='git commit -m'

