###############################################################################
# Navigation                                                                  #
###############################################################################
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

###############################################################################
# Listing                                                                     #
###############################################################################
alias ls='lsd'
alias ll='lsd -l'
alias lla='lsd -la'

alias cat='bat'

###############################################################################
# Git                                                                         #
###############################################################################
alias gcl='git clone'
alias ga='git add'
alias gc='git commit -m'

